<a href="https://colab.research.google.com/github/devendrapandey2005/data-visualization/blob/main/student_performance_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [83]:
df = pd.read_csv('/content/StudentsPerformance.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [11]:
df['test preparation course'].unique()

array(['none', 'completed'], dtype=object)

In [84]:
df.rename(columns = {'race/ethnicity':'groups'},inplace = True)

In [81]:
df

,gender,group,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

GROUP BY

In [85]:
groups = df.groupby('groups')#this create a group by object

In [53]:
print(groups)#address of the group

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7bb33ce5c510>

In [54]:
for group,df in groups:
  print(df)
  print(group)

     gender   groups parental level of education         lunch  \
32   female  group E             master's degree  free/reduced
34     male  group E                some college      standard
35     male  group E          associate's degree      standard
44   female  group E          associate's degree  free/reduced
50     male  group E                some college      standard
..      ...      ...                         ...           ...
962  female  group E          associate's degree      standard
968  female  group E          associate's degree      standard
987    male  group E            some high school      standard
990    male  group E                 high school  free/reduced
995  female  group E             master's degree      standard

    test preparation course  math score  reading score  writing score
32                     none          56             72             65
34                     none          97             87             82
35                completed          81             81             79
44                     none          50             56             54
50                     none          53             55             48
..                      ...         ...            ...            ...
962                    none         100            100            100
968                    none          68             76             67
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95

[140 rows x 8 columns]
group E

In [55]:
groups.sum(numeric_only=True)

         math score  reading score  writing score
groups
group E       10335          10224           9997

In [56]:
groups.mean(numeric_only=True)

         math score  reading score  writing score
groups
group E   73.821429      73.028571      71.407143

In [57]:
groups.var(numeric_only=True)

         math score  reading score  writing score
groups
group E  241.313207     221.236588     228.430164

In [58]:
groups.max(numeric_only=True)

         math score  reading score  writing score
groups
group E         100            100            100

In [59]:
groups.count()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group E,140,140,140,140,140,140,140

In [60]:
#find that group which scored highest total in math
print(groups['math score'].sum().sort_values().tail(1))

groups
group E    10335
Name: math score, dtype: int64

In [61]:
#find that group scored highest avg in writing
print(groups['writing score'].mean().sort_values().tail(1))

groups
group E    71.407143
Name: writing score, dtype: float64

In [62]:
#find that perental level of education which has highest total in reading score
print(df.groupby('parental level of education')['reading score'].sum().sort_values().tail(1))

parental level of education
associate's degree    2879
Name: reading score, dtype: int64

In [63]:
df.sample()

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
915,female,group E,some college,standard,none,68,70,66

groups yeh batata hai ki column ka data kis kis index pr present hai

In [64]:
df.groupby('parental level of education').groups

{'associate's degree': [35, 44, 51, 56, 83, 107, 149, 190, 216, 246, 286, 297, 332, 349, 375, 479, 503, 532, 533, 554, 691, 719, 726, 755, 779, 795, 797, 802, 868, 873, 884, 886, 891, 894, 926, 928, 955, 962, 968], 'bachelor's degree': [60, 114, 206, 241, 293, 386, 458, 476, 538, 566, 592, 616, 624, 700, 757, 881, 909, 916], 'high school': [137, 156, 182, 186, 197, 207, 214, 263, 277, 321, 415, 419, 574, 593, 643, 647, 807, 836, 937, 949, 950, 990], 'master's degree': [32, 79, 164, 225, 685, 845, 861, 995], 'some college': [34, 50, 97, 124, 132, 142, 161, 243, 255, 269, 306, 351, 370, 385, 392, 411, 451, 462, 499, 517, 525, 602, 608, 638, 676, 686, 689, 725, 734, 751, 798, 822, 852, 890, 915], 'some high school': [76, 171, 233, 289, 383, 390, 545, 581, 711, 727, 786, 793, 813, 853, 895, 925, 952, 987]}

In [65]:
df.groupby('gender').ngroups

2

In [68]:
df.groupby('groups').ngroups

1

In [88]:
len(df.groupby('groups'))

5

In [87]:
df.groupby('groups').size()

groups
group A     89
group B    190
group C    319
group D    262
group E    140
dtype: int64

In [86]:
groups.indices

{'group A': array([  3,  13,  14,  25,  46,  61,  62,  72,  77,  82,  88, 112, 129,
        143, 150, 151, 170, 228, 250, 296, 300, 305, 327, 356, 365, 368,
        378, 379, 384, 395, 401, 402, 423, 428, 433, 442, 444, 464, 467,
        468, 483, 489, 490, 506, 511, 539, 546, 571, 575, 576, 586, 589,
        591, 597, 614, 623, 635, 651, 653, 688, 697, 702, 705, 731, 741,
        769, 778, 805, 810, 811, 816, 820, 830, 832, 837, 851, 892, 902,
        911, 936, 943, 960, 966, 972, 974, 983, 985, 988, 994]),
 'group B': array([  0,   2,   5,   6,   7,   9,  12,  17,  21,  26,  31,  39,  42,
         43,  45,  65,  68,  75,  80,  81,  94,  96, 100, 103, 108, 109,
        116, 121, 125, 126, 136, 146, 152, 157, 158, 160, 162, 167, 168,
        176, 178, 188, 192, 198, 199, 203, 208, 209, 215, 218, 219, 221,
        224, 232, 238, 247, 248, 252, 258, 274, 279, 284, 285, 287, 288,
        295, 303, 308, 310, 311, 318, 329, 333, 335, 338, 342, 346, 350,
        355, 360, 361, 380, 396, 398, 406, 407, 413, 424, 443, 448, 449,
        459, 461, 474, 480, 484, 488, 494, 498, 501, 505, 507, 513, 514,
        519, 534, 551, 552, 558, 564, 565, 568, 570, 577, 578, 596, 609,
        621, 626, 631, 632, 636, 642, 644, 645, 648, 654, 655, 667, 675,
        681, 682, 684, 701, 704, 714, 715, 722, 724, 730, 737, 744, 749,
        759, 763, 765, 767, 770, 772, 774, 775, 776, 781, 782, 785, 787,
        790, 794, 803, 809, 815, 818, 823, 829, 833, 834, 838, 842, 843,
        855, 856, 858, 867, 870, 872, 882, 896, 897, 906, 914, 919, 923,
        944, 946, 948, 969, 976, 980, 982, 991]),
 'group C': array([  1,   4,  10,  15,  16,  18,  19,  23,  27,  28,  40,  41,  47,
         49,  52,  54,  55,  59,  63,  67,  69,  73,  74,  85,  86,  90,
         91,  92,  93,  95, 104, 105, 111, 115, 119, 120, 122, 131, 133,
        135, 138, 141, 145, 147, 155, 163, 165, 166, 169, 173, 174, 175,
        177, 180, 181, 184, 185, 189, 194, 196, 200, 202, 204, 211, 212,
        213, 217, 222, 226, 229, 231, 234, 239, 245, 249, 256, 257, 259,
        260, 261, 262, 266, 270, 271, 275, 276, 278, 290, 292, 298, 302,
        304, 307, 313, 314, 315, 317, 320, 322, 323, 324, 325, 326, 328,
        330, 331, 334, 337, 340, 341, 345, 347, 352, 353, 354, 357, 362,
        364, 366, 367, 371, 381, 382, 387, 393, 394, 397, 400, 404, 405,
        414, 416, 417, 420, 425, 426, 427, 429, 430, 431, 432, 434, 435,
        438, 440, 445, 447, 450, 452, 453, 454, 455, 460, 463, 465, 469,
        470, 471, 472, 482, 485, 487, 491, 492, 493, 496, 502, 508, 509,
        515, 521, 523, 524, 526, 527, 529, 530, 531, 535, 536, 540, 542,
        547, 548, 549, 550, 555, 556, 557, 561, 562, 572, 573, 585, 587,
        588, 590, 594, 595, 601, 605, 606, 607, 611, 612, 613, 615, 619,
        620, 622, 629, 633, 650, 656, 660, 661, 663, 665, 666, 668, 670,
        672, 673, 677, 683, 690, 692, 694, 696, 699, 707, 710, 716, 717,
        718, 720, 723, 729, 732, 735, 736, 739, 742, 743, 747, 748, 752,
        753, 754, 760, 766, 773, 777, 783, 784, 788, 789, 799, 800, 801,
        804, 808, 812, 814, 819, 824, 825, 826, 827, 831, 835, 839, 841,
        846, 848, 850, 854, 857, 859, 860, 863, 864, 866, 869, 871, 874,
        875, 877, 880, 885, 887, 901, 908, 912, 913, 917, 918, 921, 929,
        930, 933, 934, 940, 942, 945, 953, 954, 956, 959, 963, 967, 971,
        975, 977, 979, 984, 986, 996, 997]),
 'group D': array([  8,  11,  20,  22,  24,  29,  30,  33,  36,  37,  38,  48,  53,
         57,  58,  64,  66,  70,  71,  78,  84,  87,  89,  98,  99, 101,
        102, 106, 110, 113, 117, 118, 123, 127, 128, 130, 134, 139, 140,
        144, 148, 153, 154, 159, 172, 179, 183, 187, 191, 193, 195, 201,
        205, 210, 220, 223, 227, 230, 235, 236, 237, 240, 242, 244, 251,
        253, 254, 264, 265, 267, 268, 272, 273, 280, 281, 282, 283, 291,
        294, 299, 301, 309, 312, 316, 319, 336, 339, 343, 344, 348, 358,
        359, 363, 369, 372, 373, 374, 376, 377, 388, 389, 391, 399, 403,
        408, 409, 410, 412, 418, 421, 422, 436, 437, 439, 441, 446, 456,
        457, 466, 473, 475, 477, 478, 481, 486, 495, 497, 500, 504, 510,
        512, 516, 518, 520, 522, 528, 537, 541, 543, 544, 553, 559, 560,
        563, 567, 569, 579, 580, 582, 583, 584, 598, 599, 600, 603, 604,
        610, 617, 618, 625, 627, 628, 630, 634, 637, 639, 640, 641, 646,
        649, 652, 657, 658, 659, 662, 664, 669, 671, 674, 678, 679, 680,
        687, 693, 695, 698, 703, 706, 708, 709, 712, 713, 721, 728, 733,
        738, 740, 745, 746, 750, 756, 758, 761, 762, 764, 768, 771, 780,
        791, 792, 796, 806, 817, 821, 828, 840, 844, 847, 849, 862, 865,
        876, 878, 879, 883, 888, 889, 893, 898, 899, 900, 903, 904, 905,
        907, 910, 920, 922, 924, 927, 931, 932, 935, 938, 939, 941, 947,
        951, 957, 958, 961, 964, 965, 970, 973, 978, 981, 989, 992, 993,
        998, 999]),
 'group E': array([ 32,  34,  35,  44,  50,  51,  56,  60,  76,  79,  83,  97, 107,
        114, 124, 132, 137, 142, 149, 156, 161, 164, 171, 182, 186, 190,
        197, 206, 207, 214, 216, 225, 233, 241, 243, 246, 255, 263, 269,
        277, 286, 289, 293, 297, 306, 321, 332, 349, 351, 370, 375, 383,
        385, 386, 390, 392, 411, 415, 419, 451, 458, 462, 476, 479, 499,
        503, 517, 525, 532, 533, 538, 545, 554, 566, 574, 581, 592, 593,
        602, 608, 616, 624, 638, 643, 647, 676, 685, 686, 689, 691, 700,
        711, 719, 725, 726, 727, 734, 751, 755, 757, 779, 786, 793, 795,
        797, 798, 802, 807, 813, 822, 836, 845, 852, 853, 861, 868, 873,
        881, 884, 886, 890, 891, 894, 895, 909, 915, 916, 925, 926, 928,
        937, 949, 950, 952, 955, 962, 968, 987, 990, 995])}

In [94]:
df['math score'].nunique()

81

In [95]:
print(groups['math score'].unique().loc['group D'])

[ 64  40  66  44  74  62  69  50  75  57  88  52  58  59  45  63  61  42
  71  73  65  68  85  87  77  51  78  82  89  76  54  79  97  80  56  86
  47  53  70  90  49  67  35  27  60  26  55  29  81  84  95 100  41  43
  46  98  72  48  39  93  92]

In [96]:
groups.count()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group A,89,89,89,89,89,89,89
group B,190,190,190,190,190,190,190
group C,319,319,319,319,319,319,319
group D,262,262,262,262,262,262,262
group E,140,140,140,140,140,140,140

In [97]:
groups.first()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group A,male,associate's degree,free/reduced,none,47,57,44
group B,female,bachelor's degree,standard,none,72,72,74
group C,female,some college,standard,completed,69,90,88
group D,male,high school,free/reduced,completed,64,64,67
group E,female,master's degree,free/reduced,none,56,72,65

In [98]:
groups.last()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
groups,,,,,,,
group A,male,high school,standard,none,63,63,62
group B,female,some high school,standard,completed,65,82,78
group C,female,high school,free/reduced,completed,59,71,65
group D,female,some college,free/reduced,none,77,86,86
group E,female,master's degree,standard,completed,88,99,95

In [99]:
groups.get_group('group A')

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
25,male,group A,master's degree,free/reduced,none,73,74,72
46,female,group A,associate's degree,standard,completed,55,65,62
...,...,...,...,...,...,...,...,...
974,female,group A,some college,standard,none,54,63,67
983,female,group A,some college,standard,completed,78,87,91
985,male,group A,high school,standard,none,57,51,54
988,female,group A,some high school,free/reduced,none,44,45,45
994,male,group A,high school,standard,none,63,63,62

In [102]:
groups.get_group('group A').head(5)

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
25,male,group A,master's degree,free/reduced,none,73,74,72
46,female,group A,associate's degree,standard,completed,55,65,62

In [104]:
groups.agg(
    {
        'math score':'max',
        'reading score':'mean',
        'writing score':'sum'
    }
)

         math score  reading score  writing score
groups
group A         100      64.674157           5578
group B          97      67.352632          12464
group C          98      69.103448          21637
group D         100      70.030534          18378
group E         100      73.028571           9997

In [105]:
groups.agg(
    {
        'math score':['max','min'],
        'reading score':['mean','std'],
        'writing score':['sum','min','max']
    }
)

        math score     reading score            writing score
               max min          mean        std           sum min  max
groups
group A        100  28     64.674157  15.543762          5578  19   97
group B         97   8     67.352632  15.177499         12464  15   96
group C         98   0     69.103448  13.997033         21637  10  100
group D        100  26     70.030534  13.895306         18378  32  100
group E        100  30     73.028571  14.874024          9997  22  100